### ISSUE TITLE
Is there a page that describes better this project?

### ISSUE THREAD

**Issue by casainho** [fabiobaltieri/spotlight#1]
For what I can understand, there is an hardware, firmware (probably NRF52xxx) and then a Garmin CIQ. I wish I could see more details of all this, lime some pictures.

I am trying to develop a firmware for a NRF52840 board to send data by ANT to Garmin Edge, to have several data fields, each one connecting to a unique ANT channel and receive data from an EBike that uses the NRF52840 board. I think I will learn a lot with this project, thanks for sharing!!!!!

And here the link for our OpenSource EBike project in case you are curious: https://opensourceebike.github.io/

**Comment by fabiobaltieri** [comment]
HI! Yeah the project probably deserves a bit of a writeup, the bit that turned out to be practical is the actik-retrofit-r1 in hardware, I posted a couple of pictures here: https://fabiobaltieri.com/2019/09/21/design-analysis-of-a-petzl-actik-core-headlamp/, unfortunately though it's incredibly tedious to solder to the LED board.

There's still some useful stuff in the code, the communication part is pretty much self contained in firmware/telemetry.c and ciq-app/source/AntDevice.mc. Out of the box it builds for the nRF52832 it should be easy to port to any other nRF52.

The CIQ Datafield APIs don't really give you a way to connect one custom ANT device and use it in multiple datafields, so yeah you could use one ANT channel per field but frankly that's pretty ugly (more power consumption, more channel collisions, channels are limited etc...). You'd probably be better off doing a datafield that detects when it's placed on a large slot and displays multiple values.

Good luck!

**Comment by casainho** [comment]
Meanwhile I found your site and your Youtube and I could figure out :-)

So, thanks to your code I was able to have for testing 2 data fields with his own unique ANT channel and it works well as expected. I am now blocked because I am also using ANT+ LEV and for some reason if I enable ANT+ LEV it works but the ANT generic channels stop to work... eheh :-)

So on your Youtube I see a video of lights wireless controlled on your bicycle helmet and now the control of the head lamps... so cycling and trail run!! that is something I am being enjoying also!! I am developing OpenSource EBike technology and knowledge over the years but I wish to be involved in future on "ELegs", the same concept as EBike but for running in outdoors - you know, exeskeleton but with focus on sports, to help people go more outside to mountains!!
